### ISSUE TITLE
`jq` installation no longer required

### ISSUE THREAD

**Issue by joshwlewis** [heroku/nodejs-engine-buildpack#52]
heroku/heroku:16-build, heroku/heroku:18-build both ship with `jq` now. Since we were only installing `jq` as a build layer, we shouldn't need to install it as a part of this buildpack anymore.

```
▹ docker run -it heroku/heroku:18-build
root@f6c12c4c725e:/# jq --version
jq-1.5-1-a5b5cbe

**Comment by danielleadams** [comment]
Fixed in the linked PR.
